Create a connection
SuhailaAhmed/GP_Backend pull request #5
Opened 2023-02-22 18:11 UTC by SuhailaAhmed

2023-02-22 18:40 UTC, Suleiman99Hesham commented on accounts/views/connection_views.py
> +        "Post",
`POST` not `Post`

2023-02-22 18:42 UTC, Suleiman99Hesham commented on accounts/views/connection_views.py
> +from rest_framework.decorators import api_view, permission_classes, parser_classes
unneeded import: `parser_classes`

2023-02-22 18:42 UTC, Suleiman99Hesham commented on accounts/views/connection_views.py
> +from rest_framework.parsers import FileUploadParser, FormParser, MultiPartParser
don't need this line

2023-02-22 19:00 UTC, Suleiman99Hesham commented on accounts/serializers/connection.py
> +    email = serializers.EmailField(source="account.email", read_only=True)
we don't need to return the email of account inside the `ConnectionSerializer`

2023-02-22 19:01 UTC, Suleiman99Hesham commented on accounts/serializers/connection.py
> +        exclude = ["account"]
don't forget to remove this too

2023-02-22 19:07 UTC, Suleiman99Hesham commented on accounts/admin.py
> +    list_display = ("account", "name", "relation", "age", "address", "biograghy", "created_at", "updated_at")
- these fields are too much to display, display `name`, `account`, `age`, and `relation` respectively.
- custom `account` column to view the the name if it wasn't

2023-02-22 19:08 UTC, Suleiman99Hesham commented on accounts/admin.py
> +    fields = ("account", "name", "relation", "age", "address", "biograghy", "image")
- don't override the `fields` attribute, so remove this line

2023-02-22 19:10 UTC, Suleiman99Hesham commented on accounts/admin.py
> +    search_fields = ("name", "relation")
- make `search_fields` be ` ('name,' 'account__name') `

2023-02-22 19:11 UTC, Suleiman99Hesham commented on accounts/admin.py
> +    readonly_fields = ("account", "created_at", "updated_at")
let `account` to be readable, as we can use it as a link to the `account` data

2023-02-22 19:13 UTC, Suleiman99Hesham commented on accounts/models/connection.py
> +        return self.name
- check if `name` exists, if not return the id of the `Connection` instance as `Connection_{id}`

2023-02-22 19:16 UTC, Suleiman99Hesham commented on accounts/swagger/connection.py
> +    request_body= openapi.Schema(type=openapi.TYPE_OBJECT, required= ['name', 'relation'],
- remove `name` and `relation` from required fields as they are not required.
- add `image` to the required fields in addition to adding the as input in `properties`

2023-02-22 19:19 UTC, Suleiman99Hesham commented on accounts/views/connection_views.py
> +            return JsonResponse({"error": "missing `relation` field"}, status=400)
- `name` and `relation` are not required, make `image` instead.

2023-02-22 19:19 UTC, Suleiman99Hesham commented on accounts/views/connection_views.py
> +        connection_serialized = ConnectionSerializer(data=request.data, partial=True)
- you missed passing the instance to the serializer.

2023-02-22 19:25 UTC, Suleiman99Hesham requested changes
- add some changes to `Connection` Model:
  - please make `name ` and `relation ` not required.
  - it's enough to make the `address ` just 100 characters.
  - rename `biograghy` field to `biography` and let `max_length` to be `4000`

2023-03-14 14:45 UTC, SuhailaAhmed commented on accounts/admin.py
> +    list_display = ("account", "name", "relation", "age", "address", "biograghy", "created_at", "updated_at")
what do you mean by "custom `account` column to view the the name if it wasn't"

2023-03-21 11:26 UTC, Suleiman99Hesham commented on accounts/admin.py
> +    list_display = ("account", "name", "relation", "age", "address", "biograghy", "created_at", "updated_at")
done

2023-03-21 11:48 UTC, Suleiman99Hesham approved these changes

2023-03-21 11:50 UTC, merged